local str = require('nature.core.string')
local _M = {}

_M["application/vnd.ctc-posml"] = { "pml" }
_M["application/vnd.cups-ppd"] = { "ppd" }
_M["application/vnd.curl.car"] = { "car" }
_M["application/vnd.curl.pcurl"] = { "pcurl" }
_M["application/vnd.dart"] = { "dart" }
_M["application/vnd.data-vision.rdz"] = { "rdz" }
_M["application/vnd.dbf"] = { "dbf" }
_M["application/vnd.dece.data"] = { "uvf", "uvvf", "uvd", "uvvd" }
_M["application/vnd.dece.ttml+xml"] = { "uvt", "uvvt" }
_M["application/vnd.dece.unspecified"] = { "uvx", "uvvx" }
_M["application/vnd.dece.zip"] = { "uvz", "uvvz" }
_M["application/vnd.denovo.fcselayout-link"] = { "fe_launch" }
_M["application/vnd.dna"] = { "dna" }
_M["application/vnd.dolby.mlp"] = { "mlp" }
_M["application/vnd.dpgraph"] = { "dpg" }
_M["application/vnd.dreamfactory"] = { "dfac" }
_M["application/vnd.ds-keypoint"] = { "kpxx" }
_M["application/vnd.dvb.ait"] = { "ait" }
_M["application/vnd.dvb.service"] = { "svc" }
_M["application/vnd.dynageo"] = { "geo" }
_M["application/vnd.ecowin.chart"] = { "mag" }
_M["application/vnd.enliven"] = { "nml" }
_M["application/vnd.epson.esf"] = { "esf" }
_M["application/vnd.epson.msf"] = { "msf" }
_M["application/vnd.epson.quickanime"] = { "qam" }
_M["application/vnd.epson.salt"] = { "slt" }
_M["application/vnd.epson.ssf"] = { "ssf" }
_M["application/vnd.eszigno3+xml"] = { "es3", "et3" }
_M["application/emma+xml"] = { "emma" }
_M["application/emotionml+xml"] = { "emotionml" }
_M["application/epub+zip"] = { "epub" }
_M["application/exi"] = { "exi" }
_M["chemical/x-csml"] = { "csml" }
_M["application/fdt+xml"] = { "fdt" }
_M["font/collection"] = { "ttc" }
_M["application/font-tdpfr"] = { "pfr" }
_M["application/geo+json"] = { "geojson" }
_M["application/gml+xml"] = { "gml" }
_M["application/gpx+xml"] = { "gpx" }
_M["application/gxf"] = { "gxf" }
_M["application/gzip"] = { "gz" }
_M["application/hjson"] = { "hjson" }
_M["image/g3fax"] = { "g3" }
_M["application/hyperstudio"] = { "stk" }
_M["application/inkml+xml"] = { "ink", "inkml" }
_M["image/ief"] = { "ief" }
_M["application/ipfix"] = { "ipfix" }
_M["application/its+xml"] = { "its" }
_M["image/jpeg"] = { "jpeg", "jpg", "jpe" }
_M["application/java-archive"] = { "jar", "war", "ear" }
_M["image/jph"] = { "jph" }
_M["application/java-serialized-object"] = { "ser" }
_M["image/jphc"] = { "jhc" }
_M["application/java-vm"] = { "class" }
_M["image/jpm"] = { "jpm" }
_M["application/javascript"] = { "js", "mjs" }
_M["image/jpx"] = { "jpx", "jpf" }
_M["application/json"] = { "json", "map" }
_M["application/json5"] = { "json5" }
_M["image/jxsc"] = { "jxsc" }
_M["application/jsonml+json"] = { "jsonml" }
_M["image/jxsi"] = { "jxsi" }
_M["application/ld+json"] = { "jsonld" }
_M["application/lgr+xml"] = { "lgr" }
_M["application/lost+xml"] = { "lostxml" }
_M["application/mac-binhex40"] = { "hqx" }
_M["application/mac-compactpro"] = { "cpt" }
_M["application/mads+xml"] = { "mads" }
_M["application/manifest+json"] = { "webmanifest" }
_M["application/marc"] = { "mrc" }
_M["image/tiff-fx"] = { "tfx" }
_M["application/marcxml+xml"] = { "mrcx" }
_M["image/vnd.adobe.photoshop"] = { "psd" }
_M["application/mathematica"] = { "ma", "nb", "mb" }
_M["image/vnd.airzip.accelerator.azv"] = { "azv" }
_M["application/mathml+xml"] = { "mathml" }
_M["application/mbox"] = { "mbox" }
_M["application/mediaservercontrol+xml"] = { "mscml" }
_M["application/metalink+xml"] = { "metalink" }
_M["application/mets+xml"] = { "mets" }
_M["application/applixware"] = { "aw" }
_M["application/atom+xml"] = { "atom" }
_M["application/atomcat+xml"] = { "atomcat" }
_M["application/atomdeleted+xml"] = { "atomdeleted" }
_M["application/atomsvc+xml"] = { "atomsvc" }
_M["application/atsc-dwd+xml"] = { "dwd" }
_M["application/atsc-held+xml"] = { "held" }
_M["application/atsc-rsat+xml"] = { "rsat" }
_M["application/bdoc"] = { "bdoc" }
_M["application/calendar+xml"] = { "xcs" }
_M["application/ccxml+xml"] = { "ccxml" }
_M["application/cdfx+xml"] = { "cdfx" }
_M["application/cdmi-capability"] = { "cdmia" }
_M["application/cdmi-container"] = { "cdmic" }
_M["application/cdmi-domain"] = { "cdmid" }
_M["application/cdmi-object"] = { "cdmio" }
_M["application/cdmi-queue"] = { "cdmiq" }
_M["application/cu-seeme"] = { "cu" }
_M["text/vnd.sun.j2me.app-descriptor"] = { "jad" }
_M["application/dash+xml"] = { "mpd" }
_M["text/vnd.wap.wml"] = { "wml" }
_M["application/davmount+xml"] = { "davmount" }
_M["text/x-fortran"] = { "f", "for", "f77", "f90" }
_M["text/x-handlebars-template"] = { "hbs" }
_M["text/x-java-source"] = { "java" }
_M["text/x-lua"] = { "lua" }
_M["text/x-markdown"] = { "mkd" }
_M["text/x-nfo"] = { "nfo" }
_M["text/x-opml"] = { "opml" }
_M["text/x-org"] = { "org" }
_M["text/x-pascal"] = { "p", "pas" }
_M["text/x-processing"] = { "pde" }
_M["text/x-sass"] = { "sass" }
_M["text/x-scss"] = { "scss" }
_M["text/x-setext"] = { "etx" }
_M["text/x-sfv"] = { "sfv" }
_M["text/x-suse-ymp"] = { "ymp" }
_M["image/vnd.microsoft.icon"] = { "ico" }
_M["image/vnd.ms-dds"] = { "dds" }
_M["image/vnd.ms-modi"] = { "mdi" }
_M["image/vnd.ms-photo"] = { "wdp" }
_M["image/vnd.net-fpx"] = { "npx" }
_M["image/vnd.pco.b16"] = { "b16" }
_M["image/vnd.tencent.tap"] = { "tap" }
_M["image/vnd.valve.source.texture"] = { "vtf" }
_M["image/vnd.wap.wbmp"] = { "wbmp" }
_M["video/h261"] = { "h261" }
_M["video/h263"] = { "h263" }
_M["video/h264"] = { "h264" }
_M["video/iso.segment"] = { "m4s" }
_M["video/jpeg"] = { "jpgv" }
_M["video/jpm"] = { "jpm", "jpgm" }
_M["video/mj2"] = { "mj2", "mjp2" }
_M["video/mp2t"] = { "ts" }
_M["video/mp4"] = { "mp4", "mp4v", "mpg4" }
_M["video/mpeg"] = { "mpeg", "mpg", "mpe", "m1v", "m2v" }
_M["image/x-rgb"] = { "rgb" }
_M["image/x-tga"] = { "tga" }
_M["image/x-xbitmap"] = { "xbm" }
_M["image/x-xpixmap"] = { "xpm" }
_M["image/x-xwindowdump"] = { "xwd" }
_M["message/disposition-notification"] = { "disposition-notification" }
_M["message/global"] = { "u8msg" }
_M["audio/x-m4a"] = { "m4a" }
_M["message/global-delivery-status"] = { "u8dsn" }
_M["message/global-disposition-notification"] = { "u8mdn" }
_M["message/global-headers"] = { "u8hdr" }
_M["message/rfc822"] = { "eml", "mime" }
_M["audio/x-pn-realaudio-plugin"] = { "rmp" }
_M["message/vnd.wfa.wsc"] = { "wsc" }
_M["model/3mf"] = { "3mf" }
_M["model/gltf+json"] = { "gltf" }
_M["model/gltf-binary"] = { "glb" }
_M["model/iges"] = { "igs", "iges" }
_M["model/mesh"] = { "msh", "mesh", "silo" }
_M["application/vnd.fdf"] = { "fdf" }
_M["application/vnd.fdsn.mseed"] = { "mseed" }
_M["model/mtl"] = { "mtl" }
_M["application/vnd.fdsn.seed"] = { "seed", "dataless" }
_M["model/obj"] = { "obj" }
_M["model/stl"] = { "stl" }
_M["model/vnd.collada+xml"] = { "dae" }
_M["model/vnd.dwf"] = { "dwf" }
_M["model/vnd.gdl"] = { "gdl" }
_M["model/vnd.gtw"] = { "gtw" }
_M["application/vnd.framemaker"] = { "fm", "frame", "maker", "book" }
_M["model/vnd.mts"] = { "mts" }
_M["model/vnd.opengex"] = { "ogex" }
_M["application/vnd.frogans.fnc"] = { "fnc" }
_M["model/vnd.parasolid.transmit.binary"] = { "x_b" }
_M["application/vnd.frogans.ltf"] = { "ltf" }
_M["model/vnd.parasolid.transmit.text"] = { "x_t" }
_M["application/vnd.fsc.weblaunch"] = { "fsc" }
_M["model/vnd.usdz+zip"] = { "usdz" }
_M["application/vnd.fujitsu.oasys"] = { "oas" }
_M["model/vnd.valve.source.compiled-map"] = { "bsp" }
_M["application/vnd.fujitsu.oasys2"] = { "oa2" }
_M["model/vnd.vtu"] = { "vtu" }
_M["application/vnd.fujitsu.oasys3"] = { "oa3" }
_M["model/vrml"] = { "wrl", "vrml" }
_M["application/vnd.fujitsu.oasysgp"] = { "fg5" }
_M["model/x3d+binary"] = { "x3db", "x3dbz" }
_M["model/x3d+fastinfoset"] = { "x3db" }
_M["model/x3d+vrml"] = { "x3dv", "x3dvz" }
_M["application/vnd.fujixerox.docuworks"] = { "xdw" }
_M["model/x3d+xml"] = { "x3d", "x3dz" }
_M["application/vnd.fujixerox.docuworks.binder"] = { "xbd" }
_M["model/x3d-vrml"] = { "x3dv" }
_M["text/cache-manifest"] = { "appcache", "manifest" }
_M["application/vnd.geonext"] = { "gxt" }
_M["text/calendar"] = { "ics", "ifb" }
_M["application/vnd.geoplan"] = { "g2w" }
_M["text/coffeescript"] = { "coffee", "litcoffee" }
_M["text/css"] = { "css" }
_M["application/vnd.google-apps.presentation"] = { "gslides" }
_M["text/csv"] = { "csv" }
_M["application/vnd.google-apps.spreadsheet"] = { "gsheet" }
_M["text/html"] = { "html", "htm", "shtml" }
_M["application/vnd.groove-account"] = { "gac" }
_M["application/vnd.groove-help"] = { "ghf" }
_M["text/jade"] = { "jade" }
_M["application/vnd.groove-identity-message"] = { "gim" }
_M["text/jsx"] = { "jsx" }
_M["application/vnd.groove-tool-message"] = { "gtm" }
_M["text/less"] = { "less" }
_M["application/vnd.groove-tool-template"] = { "tpl" }
_M["text/markdown"] = { "markdown", "md" }
_M["application/vnd.groove-vcard"] = { "vcg" }
_M["text/mathml"] = { "mml" }
_M["application/vnd.hal+xml"] = { "hal" }
_M["text/mdx"] = { "mdx" }
_M["application/vnd.handheld-entertainment+xml"] = { "zmm" }
_M["application/vnd.hbci"] = { "hbci" }
_M["application/vnd.hhe.lesson-player"] = { "les" }
_M["application/vnd.hp-hpgl"] = { "hpgl" }
_M["application/vnd.hp-hpid"] = { "hpid" }
_M["application/vnd.hp-hps"] = { "hps" }
_M["text/prs.lines.tag"] = { "dsc" }
_M["application/vnd.hp-jlyt"] = { "jlt" }
_M["application/vnd.hp-pcl"] = { "pcl" }
_M["application/vnd.hp-pclxl"] = { "pclxl" }
_M["text/richtext"] = { "rtx" }
_M["application/vnd.hydrostatix.sof-data"] = { "sfd-hdstx" }
_M["application/vnd.ibm.minipay"] = { "mpy" }
_M["application/vnd.ibm.modcap"] = { "afp", "listafp", "list3820" }
_M["text/spdx"] = { "spdx" }
_M["application/vnd.ibm.rights-management"] = { "irm" }
_M["application/vnd.ibm.secure-container"] = { "sc" }
_M["application/vnd.iccprofile"] = { "icc", "icm" }
_M["text/tab-separated-values"] = { "tsv" }
_M["application/vnd.igloader"] = { "igl" }
_M["application/vnd.immervision-ivp"] = { "ivp" }
_M["application/vnd.immervision-ivu"] = { "ivu" }
_M["application/vnd.insors.igm"] = { "igm" }
_M["application/vnd.intercon.formnet"] = { "xpw", "xpx" }
_M["application/vnd.intergeo"] = { "i2g" }
_M["text/vnd.dvb.subtitle"] = { "sub" }
_M["application/vnd.intu.qbo"] = { "qbo" }
_M["application/vnd.intu.qfx"] = { "qfx" }
_M["application/vnd.ipunplugged.rcprofile"] = { "rcprofile" }
_M["application/vnd.irepository.package+xml"] = { "irp" }
_M["application/vnd.is-xpr"] = { "xpr" }
_M["application/vnd.isac.fcs"] = { "fcs" }
_M["application/vnd.jam"] = { "jam" }
_M["application/vnd.jcp.javame.midlet-rms"] = { "rms" }
_M["application/vnd.jisp"] = { "jisp" }
_M["application/vnd.joost.joda-archive"] = { "joda" }
_M["application/vnd.kahootz"] = { "ktz", "ktr" }
_M["application/x-stuffitx"] = { "sitx" }
_M["application/x-subrip"] = { "srt" }
_M["application/x-sv4cpio"] = { "sv4cpio" }
_M["application/x-sv4crc"] = { "sv4crc" }
_M["application/x-t3vm-image"] = { "t3" }
_M["application/x-tads"] = { "gam" }
_M["application/x-tar"] = { "tar" }
_M["application/x-tcl"] = { "tcl", "tk" }
_M["application/x-tex"] = { "tex" }
_M["application/x-tex-tfm"] = { "tfm" }
_M["application/x-texinfo"] = { "texinfo", "texi" }
_M["application/x-tgif"] = { "obj" }
_M["application/x-ustar"] = { "ustar" }
_M["application/x-virtualbox-hdd"] = { "hdd" }
_M["application/x-virtualbox-ova"] = { "ova" }
_M["application/x-virtualbox-ovf"] = { "ovf" }
_M["application/x-virtualbox-vbox"] = { "vbox" }
_M["application/x-virtualbox-vbox-extpack"] = { "vbox-extpack" }
_M["application/x-virtualbox-vdi"] = { "vdi" }
_M["application/x-virtualbox-vhd"] = { "vhd" }
_M["application/x-virtualbox-vmdk"] = { "vmdk" }
_M["application/x-wais-source"] = { "src" }
_M["application/x-web-app-manifest+json"] = { "webapp" }
_M["application/x-x509-ca-cert"] = { "der", "crt", "pem" }
_M["application/x-xfig"] = { "fig" }
_M["application/x-xliff+xml"] = { "xlf" }
_M["application/x-xpinstall"] = { "xpi" }
_M["application/x-xz"] = { "xz" }
_M["application/x-zmachine"] = { "z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8" }
_M["application/xaml+xml"] = { "xaml" }
_M["application/xcap-att+xml"] = { "xav" }
_M["application/xcap-caps+xml"] = { "xca" }
_M["application/xcap-diff+xml"] = { "xdf" }
_M["application/xcap-el+xml"] = { "xel" }
_M["application/xcap-ns+xml"] = { "xns" }
_M["application/xenc+xml"] = { "xenc" }
_M["application/xhtml+xml"] = { "xhtml", "xht" }
_M["application/xliff+xml"] = { "xlf" }
_M["application/xml"] = { "xml", "xsl", "xsd", "rng" }
_M["application/xml-dtd"] = { "dtd" }
_M["application/xop+xml"] = { "xop" }
_M["application/xproc+xml"] = { "xpl" }
_M["application/xslt+xml"] = { "xsl", "xslt" }
_M["application/xspf+xml"] = { "xspf" }
_M["application/xv+xml"] = { "mxml", "xhvml", "xvml", "xvm" }
_M["application/yang"] = { "yang" }
_M["application/yin+xml"] = { "yin" }
_M["application/zip"] = { "zip" }
_M["audio/3gpp"] = { "3gpp" }
_M["image/vnd.dece.graphic"] = { "uvi", "uvvi", "uvg", "uvvg" }
_M["image/vnd.djvu"] = { "djvu", "djv" }
_M["image/vnd.dvb.subtitle"] = { "sub" }
_M["image/vnd.dwg"] = { "dwg" }
_M["image/vnd.dxf"] = { "dxf" }
_M["image/vnd.fastbidsheet"] = { "fbs" }
_M["image/vnd.fpx"] = { "fpx" }
_M["image/vnd.fst"] = { "fst" }
_M["image/vnd.fujixerox.edmics-mmr"] = { "mmr" }
_M["image/vnd.fujixerox.edmics-rlc"] = { "rlc" }
_M["application/ssml+xml"] = { "ssml" }
_M["application/swid+xml"] = { "swidtag" }
_M["application/tei+xml"] = { "tei", "teicorpus" }
_M["application/thraud+xml"] = { "tfi" }
_M["application/timestamped-data"] = { "tsd" }
_M["application/toml"] = { "toml" }
_M["application/trig"] = { "trig" }
_M["application/ttml+xml"] = { "ttml" }
_M["application/ubjson"] = { "ubj" }
_M["application/urc-ressheet+xml"] = { "rsheet" }
_M["application/urc-targetdesc+xml"] = { "td" }
_M["application/vnd.1000minds.decision-model+xml"] = { "1km" }
_M["application/x-cdlink"] = { "vcd" }
_M["application/x-cfs-compressed"] = { "cfs" }
_M["application/x-chat"] = { "chat" }
_M["application/x-chess-pgn"] = { "pgn" }
_M["application/x-chrome-extension"] = { "crx" }
_M["application/x-cocoa"] = { "cco" }
_M["application/x-conference"] = { "nsc" }
_M["application/x-cpio"] = { "cpio" }
_M["application/x-csh"] = { "csh" }
_M["application/x-debian-package"] = { "deb", "udeb" }
_M["application/x-dgc-compressed"] = { "dgc" }
_M["application/x-director"] = {
    "dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"
}
_M["application/x-doom"] = { "wad" }
_M["application/x-dtbncx+xml"] = { "ncx" }
_M["application/x-dtbook+xml"] = { "dtb" }
_M["application/x-dtbresource+xml"] = { "res" }
_M["application/x-dvi"] = { "dvi" }
_M["application/x-envoy"] = { "evy" }
_M["application/x-eva"] = { "eva" }
_M["application/x-font-bdf"] = { "bdf" }
_M["application/x-font-ghostscript"] = { "gsf" }
_M["application/x-font-linux-psf"] = { "psf" }
_M["application/x-font-pcf"] = { "pcf" }
_M["application/x-font-snf"] = { "snf" }
_M["application/x-font-type1"] = { "pfa", "pfb", "pfm", "afm" }
_M["application/x-freearc"] = { "arc" }
_M["application/x-futuresplash"] = { "spl" }
_M["application/x-gca-compressed"] = { "gca" }
_M["application/x-glulx"] = { "ulx" }
_M["application/x-gnumeric"] = { "gnumeric" }
_M["application/x-gramps-xml"] = { "gramps" }
_M["application/x-gtar"] = { "gtar" }
_M["application/x-hdf"] = { "hdf" }
_M["application/x-httpd-php"] = { "php" }
_M["application/x-install-instructions"] = { "install" }
_M["application/x-iso9660-image"] = { "iso" }
_M["application/x-java-archive-diff"] = { "jardiff" }
_M["application/x-java-jnlp-file"] = { "jnlp" }
_M["application/x-keepass2"] = { "kdbx" }
_M["application/x-latex"] = { "latex" }
_M["application/x-lua-bytecode"] = { "luac" }
_M["application/x-lzh-compressed"] = { "lzh", "lha" }
_M["application/x-makeself"] = { "run" }
_M["application/x-mie"] = { "mie" }
_M["application/x-mobipocket-ebook"] = { "prc", "mobi" }
_M["application/x-ms-application"] = { "application" }
_M["application/x-ms-shortcut"] = { "lnk" }
_M["application/x-ms-wmd"] = { "wmd" }
_M["application/x-ms-wmz"] = { "wmz" }
_M["application/x-ms-xbap"] = { "xbap" }
_M["application/x-msaccess"] = { "mdb" }
_M["application/x-msbinder"] = { "obd" }
_M["application/x-mscardfile"] = { "crd" }
_M["application/x-msclip"] = { "clp" }
_M["application/x-msdos-program"] = { "exe" }
_M["application/x-msdownload"] = { "exe", "dll", "com", "bat", "msi" }
_M["application/x-msmediaview"] = { "mvb", "m13", "m14" }
_M["application/x-msmetafile"] = { "wmf", "wmz", "emf", "emz" }
_M["application/x-msmoney"] = { "mny" }
_M["application/x-mspublisher"] = { "pub" }
_M["application/x-msschedule"] = { "scd" }
_M["application/x-msterminal"] = { "trm" }
_M["application/x-mswrite"] = { "wri" }
_M["application/x-netcdf"] = { "nc", "cdf" }
_M["application/x-ns-proxy-autoconfig"] = { "pac" }
_M["application/x-nzb"] = { "nzb" }
_M["application/x-perl"] = { "pl", "pm" }
_M["application/vnd.tao.intent-module-archive"] = { "tao" }
_M["application/x-pilot"] = { "prc", "pdb" }
_M["application/x-pkcs12"] = { "p12", "pfx" }
_M["application/x-pkcs7-certificates"] = { "p7b", "spc" }
_M["application/x-pkcs7-certreqresp"] = { "p7r" }
_M["application/x-rar-compressed"] = { "rar" }
_M["application/x-redhat-package-manager"] = { "rpm" }
_M["application/vnd.triscape.mxs"] = { "mxs" }
_M["application/x-research-info-systems"] = { "ris" }
_M["application/vnd.trueapp"] = { "tra" }
_M["application/x-sea"] = { "sea" }
_M["image/vnd.xiff"] = { "xif" }
_M["application/x-sh"] = { "sh" }
_M["image/vnd.zbrush.pcx"] = { "pcx" }
_M["application/x-shar"] = { "shar" }
_M["image/webp"] = { "webp" }
_M["application/x-shockwave-flash"] = { "swf" }
_M["image/wmf"] = { "wmf" }
_M["image/x-3ds"] = { "3ds" }
_M["image/x-cmu-raster"] = { "ras" }
_M["image/x-cmx"] = { "cmx" }
_M["image/x-freehand"] = { "fh", "fhc", "fh4", "fh5", "fh7" }
_M["image/x-icon"] = { "ico" }
_M["image/x-jng"] = { "jng" }
_M["image/x-mrsid-image"] = { "sid" }
_M["image/x-ms-bmp"] = { "bmp" }
_M["image/x-pcx"] = { "pcx" }
_M["image/x-pict"] = { "pic", "pct" }
_M["application/vnd.vcx"] = { "vcx" }
_M["image/x-portable-anymap"] = { "pnm" }
_M["image/x-portable-bitmap"] = { "pbm" }
_M["image/x-portable-graymap"] = { "pgm" }
_M["image/x-portable-pixmap"] = { "ppm" }
_M["application/vnd.visio"] = { "vsd", "vst", "vss", "vsw" }
_M["application/vnd.visionary"] = { "vis" }
_M["application/vnd.vsf"] = { "vsf" }
_M["application/vnd.wap.wbxml"] = { "wbxml" }
_M["application/vnd.wap.wmlc"] = { "wmlc" }
_M["application/vnd.wap.wmlscriptc"] = { "wmlsc" }
_M["application/vnd.webturbo"] = { "wtb" }
_M["application/vnd.wolfram.player"] = { "nbp" }
_M["application/vnd.wordperfect"] = { "wpd" }
_M["application/vnd.wqd"] = { "wqd" }
_M["application/vnd.wt.stf"] = { "stf" }
_M["application/vnd.xara"] = { "xar" }
_M["application/vnd.xfdl"] = { "xfdl" }
_M["application/vnd.yamaha.hv-dic"] = { "hvd" }
_M["application/vnd.yamaha.hv-script"] = { "hvs" }
_M["application/vnd.yamaha.hv-voice"] = { "hvp" }
_M["application/vnd.yamaha.openscoreformat"] = { "osf" }
_M["application/vnd.yamaha.openscoreformat.osfpvg+xml"] = { "osfpvg" }
_M["application/vnd.yamaha.smaf-audio"] = { "saf" }
_M["application/vnd.yamaha.smaf-phrase"] = { "spf" }
_M["application/vnd.yellowriver-custom-menu"] = { "cmp" }
_M["application/vnd.zul"] = { "zir", "zirz" }
_M["application/vnd.zzazz.deck+xml"] = { "zaz" }
_M["application/voicexml+xml"] = { "vxml" }
_M["application/wasm"] = { "wasm" }
_M["application/widget"] = { "wgt" }
_M["application/winhlp"] = { "hlp" }
_M["application/wsdl+xml"] = { "wsdl" }
_M["application/wspolicy+xml"] = { "wspolicy" }
_M["application/x-7z-compressed"] = { "7z" }
_M["application/x-abiword"] = { "abw" }
_M["application/x-ace-compressed"] = { "ace" }
_M["application/x-apple-diskimage"] = { "dmg" }
_M["application/x-arj"] = { "arj" }
_M["application/x-authorware-bin"] = { "aab", "x32", "u32", "vox" }
_M["application/x-authorware-map"] = { "aam" }
_M["application/x-authorware-seg"] = { "aas" }
_M["application/x-bcpio"] = { "bcpio" }
_M["application/x-bdoc"] = { "bdoc" }
_M["application/x-bittorrent"] = { "torrent" }
_M["application/x-blorb"] = { "blb", "blorb" }
_M["application/x-bzip"] = { "bz" }
_M["application/x-bzip2"] = { "bz2", "boz" }
_M["application/x-cbr"] = { "cbr", "cba", "cbt", "cbz", "cb7" }
_M["audio/adpcm"] = { "adp" }
_M["audio/amr"] = { "amr" }
_M["audio/basic"] = { "au", "snd" }
_M["audio/midi"] = { "mid", "midi", "kar", "rmi" }
_M["audio/mobile-xmf"] = { "mxmf" }
_M["audio/mp3"] = { "mp3" }
_M["audio/mp4"] = { "m4a", "mp4a" }
_M["audio/mpeg"] = { "mpga", "mp2", "mp2a", "mp3", "m2a", "m3a" }
_M["audio/ogg"] = { "oga", "ogg", "spx", "opus" }
_M["audio/s3m"] = { "s3m" }
_M["audio/silk"] = { "sil" }
_M["audio/vnd.dece.audio"] = { "uva", "uvva" }
_M["audio/vnd.digital-winds"] = { "eol" }
_M["audio/vnd.dra"] = { "dra" }
_M["audio/vnd.dts"] = { "dts" }
_M["audio/vnd.dts.hd"] = { "dtshd" }
_M["audio/vnd.lucent.voice"] = { "lvp" }
_M["audio/vnd.ms-playready.media.pya"] = { "pya" }
_M["audio/vnd.nuera.ecelp4800"] = { "ecelp4800" }
_M["audio/vnd.nuera.ecelp7470"] = { "ecelp7470" }
_M["audio/vnd.nuera.ecelp9600"] = { "ecelp9600" }
_M["audio/vnd.rip"] = { "rip" }
_M["audio/wav"] = { "wav" }
_M["audio/wave"] = { "wav" }
_M["audio/webm"] = { "weba" }
_M["audio/x-aac"] = { "aac" }
_M["audio/x-aiff"] = { "aif", "aiff", "aifc" }
_M["audio/x-caf"] = { "caf" }
_M["audio/x-flac"] = { "flac" }
_M["application/vnd.osgi.dp"] = { "dp" }
_M["application/vnd.osgi.subsystem"] = { "esa" }
_M["application/vnd.palm"] = { "pdb", "pqa", "oprc" }
_M["application/vnd.pawaafile"] = { "paw" }
_M["application/vnd.pg.format"] = { "str" }
_M["application/vnd.pg.osasli"] = { "ei6" }
_M["application/vnd.picsel"] = { "efif" }
_M["application/vnd.pmi.widget"] = { "wg" }
_M["application/vnd.pocketlearn"] = { "plf" }
_M["application/vnd.powerbuilder6"] = { "pbd" }
_M["application/vnd.previewsystems.box"] = { "box" }
_M["application/vnd.proteus.magazine"] = { "mgz" }
_M["application/vnd.publishare-delta-tree"] = { "qps" }
_M["application/vnd.pvi.ptid1"] = { "ptid" }
_M["application/vnd.quark.quarkxpress"] = {
    "qxd", "qxt", "qwd", "qwt", "qxl", "qxb"
}
_M["application/vnd.rar"] = { "rar" }
_M["application/vnd.realvnc.bed"] = { "bed" }
_M["application/vnd.recordare.musicxml"] = { "mxl" }
_M["application/vnd.recordare.musicxml+xml"] = { "musicxml" }
_M["application/vnd.rig.cryptonote"] = { "cryptonote" }
_M["application/vnd.rim.cod"] = { "cod" }
_M["application/vnd.rn-realmedia"] = { "rm" }
_M["application/vnd.rn-realmedia-vbr"] = { "rmvb" }
_M["application/vnd.route66.link66+xml"] = { "link66" }
_M["application/vnd.sailingtracker.track"] = { "st" }
_M["application/vnd.seemail"] = { "see" }
_M["application/vnd.sema"] = { "sema" }
_M["application/vnd.semd"] = { "semd" }
_M["application/vnd.semf"] = { "semf" }
_M["application/vnd.shana.informed.formdata"] = { "ifm" }
_M["application/vnd.shana.informed.formtemplate"] = { "itp" }
_M["application/vnd.shana.informed.interchange"] = { "iif" }
_M["application/vnd.shana.informed.package"] = { "ipk" }
_M["application/vnd.simtech-mindmapper"] = { "twd", "twds" }
_M["application/vnd.smaf"] = { "mmf" }
_M["application/vnd.smart.teacher"] = { "teacher" }
_M["application/vnd.software602.filler.form+xml"] = { "fo" }
_M["application/vnd.solent.sdkm+xml"] = { "sdkm", "sdkd" }
_M["application/vnd.spotfire.dxp"] = { "dxp" }
_M["application/vnd.spotfire.sfs"] = { "sfs" }
_M["application/vnd.stardivision.calc"] = { "sdc" }
_M["application/vnd.stardivision.draw"] = { "sda" }
_M["application/vnd.stardivision.impress"] = { "sdd" }
_M["application/vnd.stardivision.math"] = { "smf" }
_M["application/vnd.stardivision.writer"] = { "sdw", "vor" }
_M["application/vnd.stardivision.writer-global"] = { "sgl" }
_M["application/vnd.stepmania.package"] = { "smzip" }
_M["application/vnd.stepmania.stepchart"] = { "sm" }
_M["application/vnd.sun.wadl+xml"] = { "wadl" }
_M["application/vnd.sun.xml.calc"] = { "sxc" }
_M["application/vnd.sun.xml.calc.template"] = { "stc" }
_M["application/vnd.sun.xml.draw"] = { "sxd" }
_M["application/vnd.sun.xml.draw.template"] = { "std" }
_M["application/vnd.sun.xml.impress"] = { "sxi" }
_M["application/vnd.sun.xml.impress.template"] = { "sti" }
_M["application/vnd.sun.xml.math"] = { "sxm" }
_M["application/vnd.sun.xml.writer"] = { "sxw" }
_M["application/vnd.sun.xml.writer.global"] = { "sxg" }
_M["application/vnd.sun.xml.writer.template"] = { "stw" }
_M["application/vnd.sus-calendar"] = { "sus", "susp" }
_M["application/vnd.svd"] = { "svd" }
_M["application/vnd.symbian.install"] = { "sis", "sisx" }
_M["application/vnd.syncml+xml"] = { "xsm" }
_M["application/vnd.syncml.dm+wbxml"] = { "bdm" }
_M["application/vnd.syncml.dm+xml"] = { "xdm" }
_M["application/vnd.syncml.dmddf+xml"] = { "ddf" }
_M["application/docbook+xml"] = { "dbk" }
_M["application/dssc+der"] = { "dssc" }
_M["application/dssc+xml"] = { "xdssc" }
_M["application/ecmascript"] = { "es", "ecma" }
_M["application/pkix-crl"] = { "crl" }
_M["application/pkix-pkipath"] = { "pkipath" }
_M["application/pkixcmp"] = { "pki" }
_M["application/pls+xml"] = { "pls" }
_M["application/postscript"] = { "ai", "eps", "ps" }
_M["application/provenance+xml"] = { "provx" }
_M["application/prs.cww"] = { "cww" }
_M["application/pskc+xml"] = { "pskcxml" }
_M["application/raml+yaml"] = { "raml" }
_M["application/rdf+xml"] = { "rdf", "owl" }
_M["application/reginfo+xml"] = { "rif" }
_M["application/relax-ng-compact-syntax"] = { "rnc" }
_M["application/resource-lists+xml"] = { "rl" }
_M["application/resource-lists-diff+xml"] = { "rld" }
_M["application/rls-services+xml"] = { "rs" }
_M["application/route-apd+xml"] = { "rapd" }
_M["application/route-s-tsid+xml"] = { "sls" }
_M["application/route-usd+xml"] = { "rusd" }
_M["application/rpki-ghostbusters"] = { "gbr" }
_M["application/rpki-manifest"] = { "mft" }
_M["application/rpki-roa"] = { "roa" }
_M["application/rsd+xml"] = { "rsd" }
_M["application/rss+xml"] = { "rss" }
_M["application/rtf"] = { "rtf" }
_M["application/sbml+xml"] = { "sbml" }
_M["application/scvp-cv-request"] = { "scq" }
_M["application/scvp-cv-response"] = { "scs" }
_M["application/scvp-vp-request"] = { "spq" }
_M["application/scvp-vp-response"] = { "spp" }
_M["application/sdp"] = { "sdp" }
_M["application/senml+xml"] = { "senmlx" }
_M["application/sensml+xml"] = { "sensmlx" }
_M["application/set-payment-initiation"] = { "setpay" }
_M["application/set-registration-initiation"] = { "setreg" }
_M["application/shf+xml"] = { "shf" }
_M["application/sieve"] = { "siv", "sieve" }
_M["application/smil+xml"] = { "smi", "smil" }
_M["application/sparql-query"] = { "rq" }
_M["application/sparql-results+xml"] = { "srx" }
_M["application/srgs"] = { "gram" }
_M["application/srgs+xml"] = { "grxml" }
_M["application/sru+xml"] = { "sru" }
_M["application/ssdl+xml"] = { "ssdl" }
_M["application/vnd.noblenet-directory"] = { "nnd" }
_M["application/vnd.noblenet-sealer"] = { "nns" }
_M["application/vnd.noblenet-web"] = { "nnw" }
_M["application/vnd.nokia.n-gage.ac+xml"] = { "ac" }
_M["application/vnd.nokia.n-gage.data"] = { "ngdat" }
_M["application/vnd.nokia.n-gage.symbian.install"] = { "n-gage" }
_M["application/vnd.nokia.radio-preset"] = { "rpst" }
_M["application/vnd.nokia.radio-presets"] = { "rpss" }
_M["application/vnd.novadigm.edm"] = { "edm" }
_M["application/vnd.novadigm.edx"] = { "edx" }
_M["application/vnd.novadigm.ext"] = { "ext" }
_M["application/vnd.oasis.opendocument.chart"] = { "odc" }
_M["application/vnd.oasis.opendocument.chart-template"] = { "otc" }
_M["application/vnd.oasis.opendocument.database"] = { "odb" }
_M["application/vnd.oasis.opendocument.formula"] = { "odf" }
_M["application/vnd.oasis.opendocument.formula-template"] = { "odft" }
_M["application/vnd.oasis.opendocument.graphics"] = { "odg" }
_M["application/vnd.oasis.opendocument.graphics-template"] = { "otg" }
_M["application/vnd.oasis.opendocument.image"] = { "odi" }
_M["application/vnd.oasis.opendocument.image-template"] = { "oti" }
_M["application/vnd.oasis.opendocument.presentation"] = { "odp" }
_M["application/vnd.oasis.opendocument.presentation-template"] = { "otp" }
_M["application/vnd.oasis.opendocument.spreadsheet"] = { "ods" }
_M["application/vnd.oasis.opendocument.spreadsheet-template"] = { "ots" }
_M["application/vnd.oasis.opendocument.text"] = { "odt" }
_M["application/vnd.oasis.opendocument.text-master"] = { "odm" }
_M["application/vnd.oasis.opendocument.text-template"] = { "ott" }
_M["application/vnd.oasis.opendocument.text-web"] = { "oth" }
_M["application/vnd.olpc-sugar"] = { "xo" }
_M["application/vnd.oma.dd2+xml"] = { "dd2" }
_M["application/vnd.openblox.game+xml"] = { "obgx" }
_M["application/vnd.openofficeorg.extension"] = { "oxt" }
_M["application/vnd.openstreetmap.data+xml"] = { "osm" }
_M["application/vnd.openxmlformats-officedocument.presentationml.presentation"] =
{ "pptx" }
_M["application/vnd.openxmlformats-officedocument.presentationml.slide"] = {
    "sldx"
}
_M["application/vnd.openxmlformats-officedocument.presentationml.slideshow"] = {
    "ppsx"
}
_M["application/vnd.openxmlformats-officedocument.presentationml.template"] = {
    "potx"
}
_M["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"] = {
    "xlsx"
}
_M["application/vnd.openxmlformats-officedocument.spreadsheetml.template"] = {
    "xltx"
}
_M["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] =
{ "docx" }
_M["application/vnd.openxmlformats-officedocument.wordprocessingml.template"] =
{ "dotx" }
_M["application/vnd.osgeo.mapguide.package"] = { "mgp" }
_M["application/mmt-aei+xml"] = { "maei" }
_M["application/mmt-usd+xml"] = { "musd" }
_M["application/mods+xml"] = { "mods" }
_M["application/mp21"] = { "m21", "mp21" }
_M["application/mp4"] = { "mp4s", "m4p" }
_M["application/msword"] = { "doc", "dot" }
_M["application/mxf"] = { "mxf" }
_M["application/n-quads"] = { "nq" }
_M["application/n-triples"] = { "nt" }
_M["application/node"] = { "cjs" }
_M["application/octet-stream"] = {
    "bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump",
    "elc", "deploy", "exe", "dll", "deb", "dmg", "iso", "img", "msi", "msp",
    "msm", "buffer"
}
_M["application/vnd.kde.karbon"] = { "karbon" }
_M["application/vnd.kde.kchart"] = { "chrt" }
_M["application/vnd.kde.kformula"] = { "kfo" }
_M["application/oda"] = { "oda" }
_M["application/vnd.kde.kontour"] = { "kon" }
_M["application/oebps-package+xml"] = { "opf" }
_M["application/ogg"] = { "ogx" }
_M["application/vnd.kde.kspread"] = { "ksp" }
_M["application/omdoc+xml"] = { "omdoc" }
_M["application/vnd.kde.kword"] = { "kwd", "kwt" }
_M["application/onenote"] = { "onetoc", "onetoc2", "onetmp", "onepkg" }
_M["application/vnd.kenameaapp"] = { "htke" }
_M["application/vnd.kidspiration"] = { "kia" }
_M["application/vnd.kinar"] = { "kne", "knp" }
_M["application/oxps"] = { "oxps" }
_M["application/p2p-overlay+xml"] = { "relo" }
_M["application/patch-ops-error+xml"] = { "xer" }
_M["application/vnd.kodak-descriptor"] = { "sse" }
_M["application/pdf"] = { "pdf" }
_M["application/vnd.las.las+xml"] = { "lasxml" }
_M["application/pgp-encrypted"] = { "pgp" }
_M["application/vnd.llamagraphics.life-balance.desktop"] = { "lbd" }
_M["application/pics-rules"] = { "prf" }
_M["application/pkcs10"] = { "p10" }
_M["application/vnd.lotus-approach"] = { "apr" }
_M["application/pkcs7-mime"] = { "p7m", "p7c" }
_M["application/vnd.lotus-freelance"] = { "pre" }
_M["application/pkcs7-signature"] = { "p7s" }
_M["application/pkcs8"] = { "p8" }
_M["application/vnd.lotus-screencam"] = { "scm" }
_M["application/pkix-attr-cert"] = { "ac" }
_M["application/vnd.lotus-wordpro"] = { "lwp" }
_M["application/pkix-cert"] = { "cer" }
_M["application/vnd.macports.portpkg"] = { "portpkg" }
_M["application/vnd.mapbox-vector-tile"] = { "mvt" }
_M["application/vnd.mcd"] = { "mcd" }
_M["application/vnd.medcalcdata"] = { "mc1" }
_M["application/vnd.mediastation.cdkey"] = { "cdkey" }
_M["application/vnd.mfer"] = { "mwf" }
_M["application/vnd.mfmp"] = { "mfm" }
_M["application/vnd.micrografx.flo"] = { "flo" }
_M["application/vnd.micrografx.igx"] = { "igx" }
_M["application/vnd.mif"] = { "mif" }
_M["application/vnd.mobius.daf"] = { "daf" }
_M["application/vnd.mobius.dis"] = { "dis" }
_M["application/vnd.mobius.mbk"] = { "mbk" }
_M["application/vnd.mobius.mqy"] = { "mqy" }
_M["application/vnd.mobius.msl"] = { "msl" }
_M["application/vnd.mobius.plc"] = { "plc" }
_M["application/vnd.mobius.txf"] = { "txf" }
_M["application/vnd.mophun.application"] = { "mpn" }
_M["application/vnd.mophun.certificate"] = { "mpc" }
_M["application/vnd.mozilla.xul+xml"] = { "xul" }
_M["application/vnd.ms-artgalry"] = { "cil" }
_M["application/vnd.ms-cab-compressed"] = { "cab" }
_M["application/vnd.ms-excel"] = { "xls", "xlm", "xla", "xlc", "xlt", "xlw" }
_M["application/vnd.ms-excel.addin.macroenabled.12"] = { "xlam" }
_M["application/vnd.ms-excel.sheet.binary.macroenabled.12"] = { "xlsb" }
_M["application/vnd.ms-excel.sheet.macroenabled.12"] = { "xlsm" }
_M["application/vnd.ms-excel.template.macroenabled.12"] = { "xltm" }
_M["application/vnd.ms-fontobject"] = { "eot" }
_M["application/vnd.ms-htmlhelp"] = { "chm" }
_M["application/vnd.ms-ims"] = { "ims" }
_M["application/vnd.ms-lrm"] = { "lrm" }
_M["application/vnd.ms-officetheme"] = { "thmx" }
_M["application/vnd.ms-outlook"] = { "msg" }
_M["text/vnd.curl"] = { "curl" }
_M["application/vnd.ms-pki.seccat"] = { "cat" }
_M["text/vnd.curl.dcurl"] = { "dcurl" }
_M["application/vnd.ms-pki.stl"] = { "stl" }
_M["text/vnd.curl.scurl"] = { "scurl" }
_M["application/vnd.ms-powerpoint"] = { "ppt", "pps", "pot" }
_M["text/vnd.fly"] = { "fly" }
_M["application/vnd.ms-powerpoint.addin.macroenabled.12"] = { "ppam" }
_M["application/vnd.ms-powerpoint.presentation.macroenabled.12"] = { "pptm" }
_M["text/vnd.in3d.3dml"] = { "3dml" }
_M["application/vnd.ms-powerpoint.slide.macroenabled.12"] = { "sldm" }
_M["application/vnd.ms-powerpoint.slideshow.macroenabled.12"] = { "ppsm" }
_M["application/vnd.ms-powerpoint.template.macroenabled.12"] = { "potm" }
_M["application/vnd.ms-project"] = { "mpp", "mpt" }
_M["application/vnd.ms-word.document.macroenabled.12"] = { "docm" }
_M["text/vnd.wap.wmlscript"] = { "wmls" }
_M["application/vnd.ms-word.template.macroenabled.12"] = { "dotm" }
_M["text/x-asm"] = { "s", "asm" }
_M["application/vnd.ms-works"] = { "wps", "wks", "wcm", "wdb" }
_M["text/x-component"] = { "htc" }
_M["text/x-vcalendar"] = { "vcs" }
_M["text/xml"] = { "xml" }
_M["video/3gpp"] = { "3gp", "3gpp" }
_M["application/vnd.ms-wpl"] = { "wpl" }
_M["application/vnd.ms-xpsdocument"] = { "xps" }
_M["video/3gpp2"] = { "3g2" }
_M["application/vnd.mseq"] = { "mseq" }
_M["application/vnd.musician"] = { "mus" }
_M["application/vnd.muvee.style"] = { "msty" }
_M["application/vnd.mynfc"] = { "taglet" }
_M["application/vnd.neurolanguage.nlu"] = { "nlu" }
_M["application/vnd.nitf"] = { "ntf", "nitf" }
_M["video/vnd.dece.hd"] = { "uvh", "uvvh" }
_M["video/vnd.dece.mobile"] = { "uvm", "uvvm" }
_M["video/ogg"] = { "ogv" }
_M["video/vnd.dece.pd"] = { "uvp", "uvvp" }
_M["video/quicktime"] = { "qt", "mov" }
_M["video/vnd.dece.sd"] = { "uvs", "uvvs" }
_M["video/vnd.dece.video"] = { "uvv", "uvvv" }
_M["video/vnd.dvb.file"] = { "dvb" }
_M["video/vnd.fvt"] = { "fvt" }
_M["video/vnd.mpegurl"] = { "mxu", "m4u" }
_M["video/vnd.ms-playready.media.pyv"] = { "pyv" }
_M["video/vnd.uvvu.mp4"] = { "uvu", "uvvu" }
_M["video/vnd.vivo"] = { "viv" }
_M["video/webm"] = { "webm" }
_M["text/yaml"] = { "yaml", "yml" }
_M["video/x-f4v"] = { "f4v" }
_M["text/x-vcard"] = { "vcf" }
_M["video/x-fli"] = { "fli" }
_M["text/x-uuencode"] = { "uu" }
_M["video/x-flv"] = { "flv" }
_M["text/x-c"] = { "c", "cc", "cxx", "cpp", "h", "hh", "dic" }
_M["video/x-m4v"] = { "m4v" }
_M["text/vtt"] = { "vtt" }
_M["video/x-matroska"] = { "mkv", "mk3d", "mks" }
_M["video/x-mng"] = { "mng" }
_M["video/x-ms-asf"] = { "asf", "asx" }
_M["video/x-ms-vob"] = { "vob" }
_M["video/x-ms-wm"] = { "wm" }
_M["video/x-ms-wmv"] = { "wmv" }
_M["text/vnd.in3d.spot"] = { "spot" }
_M["video/x-ms-wmx"] = { "wmx" }
_M["video/x-ms-wvx"] = { "wvx" }
_M["text/vnd.graphviz"] = { "gv" }
_M["video/x-msvideo"] = { "avi" }
_M["text/vnd.fmi.flexstor"] = { "flx" }
_M["video/x-sgi-movie"] = { "movie" }
_M["video/x-smv"] = { "smv" }
_M["x-conference/x-cooltalk"] = { "ice" }
_M["text/vnd.curl.mcurl"] = { "mcurl" }
_M["text/vcard"] = { "vcard" }
_M["text/uri-list"] = { "uri", "uris", "urls" }
_M["text/turtle"] = { "ttl" }
_M["text/troff"] = { "t", "tr", "roff", "man", "me", "ms" }
_M["text/stylus"] = { "stylus", "styl" }
_M["text/slim"] = { "slim", "slm" }
_M["text/shex"] = { "shex" }
_M["text/sgml"] = { "sgml", "sgm" }
_M["text/rtf"] = { "rtf" }
_M["text/plain"] = { "txt", "text", "conf", "def", "list", "log", "in", "ini" }
_M["text/n3"] = { "n3" }
_M["image/t38"] = { "t38" }
_M["application/pgp-signature"] = { "asc", "sig" }
_M["image/sgi"] = { "sgi" }
_M["image/prs.pti"] = { "pti" }
_M["image/png"] = { "png" }
_M["image/ktx2"] = { "ktx2" }
_M["application/vnd.lotus-notes"] = { "nsf" }
_M["image/jxss"] = { "jxss" }
_M["image/jxs"] = { "jxs" }
_M["image/jxra"] = { "jxra" }
_M["application/vnd.koan"] = { "skp", "skd", "skt", "skm" }
_M["image/jp2"] = { "jp2", "jpg2" }
_M["image/jls"] = { "jls" }
_M["image/hsj2"] = { "hsj2" }
_M["image/hej2k"] = { "hej2" }
_M["image/heif-sequence"] = { "heifs" }
_M["image/heif"] = { "heif" }
_M["image/heic-sequence"] = { "heics" }
_M["image/heic"] = { "heic" }
_M["image/gif"] = { "gif" }
_M["image/fits"] = { "fits" }
_M["image/emf"] = { "emf" }
_M["image/dicom-rle"] = { "drle" }
_M["image/cgm"] = { "cgm" }
_M["image/bmp"] = { "bmp" }
_M["image/apng"] = { "apng" }
_M["font/otf"] = { "otf" }
_M["chemical/x-cmdf"] = { "cmdf" }
_M["chemical/x-cdx"] = { "cdx" }
_M["audio/xm"] = { "xm" }
_M["audio/x-realaudio"] = { "ra" }
_M["audio/x-mpegurl"] = { "m3u" }
_M["audio/x-ms-wax"] = { "wax" }
_M["audio/x-pn-realaudio"] = { "ram", "ra" }
_M["application/vnd.ezpix-album"] = { "ez2" }
_M["application/vnd.fluxtime.clip"] = { "ftc" }
_M["application/vnd.fujitsu.oasysprs"] = { "bh2" }
_M["application/vnd.3gpp.pic-bw-large"] = { "plb" }
_M["application/vnd.3gpp.pic-bw-small"] = { "psb" }
_M["application/vnd.fujixerox.ddd"] = { "ddd" }
_M["application/vnd.3gpp.pic-bw-var"] = { "pvb" }
_M["application/vnd.3gpp2.tcap"] = { "tcap" }
_M["application/vnd.3m.post-it-notes"] = { "pwn" }
_M["application/vnd.accpac.simply.aso"] = { "aso" }
_M["application/vnd.accpac.simply.imp"] = { "imp" }
_M["application/vnd.acucobol"] = { "acu" }
_M["application/vnd.fuzzysheet"] = { "fzs" }
_M["application/vnd.acucorp"] = { "atc", "acutc" }
_M["application/vnd.genomatix.tuxedo"] = { "txd" }
_M["application/vnd.adobe.air-application-installer-package+zip"] = { "air" }
_M["application/vnd.adobe.formscentral.fcdt"] = { "fcdt" }
_M["application/vnd.geogebra.file"] = { "ggb" }
_M["application/vnd.adobe.fxp"] = { "fxp", "fxpl" }
_M["application/vnd.ezpix-package"] = { "ez3" }
_M["application/vnd.adobe.xdp+xml"] = { "xdp" }
_M["application/vnd.adobe.xfdf"] = { "xfdf" }
_M["application/vnd.ahead.space"] = { "ahead" }
_M["application/vnd.airzip.filesecure.azf"] = { "azf" }
_M["application/vnd.kde.kivio"] = { "flw" }
_M["application/vnd.airzip.filesecure.azs"] = { "azs" }
_M["application/vnd.kde.kpresenter"] = { "kpr", "kpt" }
_M["application/vnd.amazon.ebook"] = { "azw" }
_M["application/vnd.americandynamics.acc"] = { "acc" }
_M["application/vnd.llamagraphics.life-balance.exchange+xml"] = { "lbe" }
_M["application/vnd.amiga.ami"] = { "ami" }
_M["application/vnd.android.package-archive"] = { "apk" }
_M["application/vnd.anser-web-certificate-issue-initiation"] = { "cii" }
_M["application/vnd.anser-web-funds-transfer-initiation"] = { "fti" }
_M["application/vnd.antix.game-component"] = { "atx" }
_M["application/vnd.unity"] = { "unityweb" }
_M["application/vnd.apple.installer+xml"] = { "mpkg" }
_M["application/vnd.umajin"] = { "umj" }
_M["application/vnd.apple.keynote"] = { "key" }
_M["application/vnd.apple.mpegurl"] = { "m3u8" }
_M["application/vnd.uiq.theme"] = { "utz" }
_M["application/vnd.apple.numbers"] = { "numbers" }
_M["application/vnd.apple.pages"] = { "pages" }
_M["application/vnd.trid.tpt"] = { "tpt" }
_M["application/vnd.apple.pkpass"] = { "pkpass" }
_M["application/vnd.aristanetworks.swi"] = { "swi" }
_M["application/vnd.astraea-software.iota"] = { "iota" }
_M["application/vnd.uoml+xml"] = { "uoml" }
_M["application/vnd.audiograph"] = { "aep" }
_M["application/vnd.ufdl"] = { "ufd", "ufdl" }
_M["application/vnd.tmobile-livetv"] = { "tmo" }
_M["application/vnd.tcpdump.pcap"] = { "pcap", "cap", "dmp" }
_M["application/x-silverlight-app"] = { "xap" }
_M["application/x-sql"] = { "sql" }
_M["application/x-stuffit"] = { "sit" }
_M["application/vnd.lotus-organizer"] = { "org" }
_M["application/vnd.lotus-1-2-3"] = { "123" }
_M["application/andrew-inset"] = { "ez" }
_M["application/vnd.flographit"] = { "gph" }
_M["application/metalink4+xml"] = { "meta4" }
_M["application/vnd.groove-injector"] = { "grv" }
_M["application/vnd.grafeq"] = { "gqf", "gqs" }
_M["application/vnd.google-earth.kmz"] = { "kmz" }
_M["application/vnd.google-earth.kml+xml"] = { "kml" }
_M["application/vnd.google-apps.document"] = { "gdoc" }
_M["application/vnd.gmx"] = { "gmx" }
_M["application/vnd.geospace"] = { "g3w" }
_M["application/vnd.geometry-explorer"] = { "gex", "gre" }
_M["application/vnd.geogebra.tool"] = { "ggt" }
_M["application/vnd.balsamiq.bmml+xml"] = { "bmml" }
_M["application/vnd.blueice.multipass"] = { "mpm" }
_M["application/vnd.bmi"] = { "bmi" }
_M["application/vnd.businessobjects"] = { "rep" }
_M["application/vnd.chemdraw+xml"] = { "cdxml" }
_M["audio/x-ms-wma"] = { "wma" }
_M["application/vnd.chipnuts.karaoke-mmd"] = { "mmd" }
_M["audio/x-matroska"] = { "mka" }
_M["application/vnd.cinderella"] = { "cdy" }
_M["audio/x-wav"] = { "wav" }
_M["application/vnd.citationstyles.style+xml"] = { "csl" }
_M["chemical/x-cif"] = { "cif" }
_M["application/vnd.claymore"] = { "cla" }
_M["chemical/x-cml"] = { "cml" }
_M["application/vnd.cloanto.rp9"] = { "rp9" }
_M["chemical/x-xyz"] = { "xyz" }
_M["application/vnd.clonk.c4group"] = { "c4g", "c4d", "c4f", "c4p", "c4u" }
_M["font/ttf"] = { "ttf" }
_M["font/woff"] = { "woff" }
_M["font/woff2"] = { "woff2" }
_M["image/aces"] = { "exr" }
_M["application/vnd.cluetrust.cartomobile-config"] = { "c11amc" }
_M["application/vnd.cluetrust.cartomobile-config-pkg"] = { "c11amz" }
_M["image/avif"] = { "avif" }
_M["application/vnd.commonspace"] = { "csp" }
_M["image/jxr"] = { "jxr" }
_M["application/vnd.contact.cmsg"] = { "cdbcmsg" }
_M["image/jxrs"] = { "jxrs" }
_M["application/vnd.cosmocaller"] = { "cmc" }
_M["image/ktx"] = { "ktx" }
_M["application/vnd.crick.clicker"] = { "clkx" }
_M["application/vnd.crick.clicker.keyboard"] = { "clkk" }
_M["image/prs.btif"] = { "btif" }
_M["application/vnd.crick.clicker.palette"] = { "clkp" }
_M["application/vnd.crick.clicker.template"] = { "clkt" }
_M["image/svg+xml"] = { "svg", "svgz" }
_M["application/vnd.crick.clicker.wordbank"] = { "clkw" }
_M["image/tiff"] = { "tif", "tiff" }
_M["application/vnd.criticaltools.wbs+xml"] = { "wbs" }
_M["model/vnd.sap.vds"] = { "vds" }

local str_split = str.split
local str_lower = str.lower
local str_get_file_ext = str.get_file_ext

local function lookup_content_type(content_type)
    if not content_type then
        return nil
    end
    local data = str_split(content_type, ";", nil, nil, 2)
    return _M[str_lower(data[1])]
end

_M.lookup_content_type = lookup_content_type

function _M.lookup(path, content_type)
    local m = str_get_file_ext(path)
    if not m then
        m = lookup_content_type(content_type)
        if m then
            m = m[1]
        end
    end

    return m
end

return _M
